// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8_GwVXZnX8LmVq-jxKhBs86s17iSbgno',
    appId: '1:310542131489:web:21646bb3eb185627339e60',
    messagingSenderId: '310542131489',
    projectId: 'fishnetlk-8f180',
    authDomain: 'fishnetlk-8f180.firebaseapp.com',
    storageBucket: 'fishnetlk-8f180.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl3Mma-tw4K6Z95RkGumrC7gxdkearCDk',
    appId: '1:310542131489:android:a30e2f64c88fc775339e60',
    messagingSenderId: '310542131489',
    projectId: 'fishnetlk-8f180',
    storageBucket: 'fishnetlk-8f180.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4eOdBorBBWQolyIaESHoysDJhWOw4nHY',
    appId: '1:310542131489:ios:5492d3c3f8c81098339e60',
    messagingSenderId: '310542131489',
    projectId: 'fishnetlk-8f180',
    storageBucket: 'fishnetlk-8f180.appspot.com',
    iosBundleId: 'com.example.fishnetlk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4eOdBorBBWQolyIaESHoysDJhWOw4nHY',
    appId: '1:310542131489:ios:6a8cfaa2ed57b9a1339e60',
    messagingSenderId: '310542131489',
    projectId: 'fishnetlk-8f180',
    storageBucket: 'fishnetlk-8f180.appspot.com',
    iosBundleId: 'com.example.fishnetlk.RunnerTests',
  );
}
